package com.example.blizzcash

//const val KEY_NAME = "name"

sealed class Screen(val route: String){
    object Welcome: Screen("welcome_screen")
    object EmailSignUp: Screen("singup_screen")
    object Options: Screen("options_screen")
    object Profile: Screen("profile_screen")
    object Home: Screen("home_screen")
    object Practice: Screen("practice_screen")
    object Courses: Screen("courses_screen")
    object Lens: Screen("lens_screen")
    object Settings : Screen("settings_screen")
    /*------------------------------------------------------------*/
    object AllowanceLesson0: Screen("allowancelesson0")
    object AllowanceLesson1: Screen("allowancelesson1")
    object AllowanceLesson2: Screen("allowancelesson2")
    object AllowanceLesson3: Screen("allowancelesson3")
    object AllowanceLesson4: Screen("allowancelesson4")
    object AllowanceLesson5: Screen("allowancelesson5")
    object AllowanceLesson6: Screen("allowancelesson6")
    object AllowanceLesson7: Screen("allowancelesson7")
    object AllowanceLesson8: Screen("allowancelesson8")
    object AllowanceLesson9: Screen("allowancelesson9")
    object SalaryLesson0: Screen("salarylesson0")
    object SalaryLesson1: Screen("salarylesson1")
    object SalaryLesson2: Screen("salarylesson2")
    object SalaryLesson3: Screen("salarylesson3")
    object SalaryLesson4: Screen("salarylesson4")
    object SalaryLesson5: Screen("salarylesson5")
    object SalaryLesson6: Screen("salarylesson6")
    object SalaryLesson7: Screen("salarylesson7")
    object SalaryLesson8: Screen("salarylesson8")
    object SalaryLesson9: Screen("salarylesson9")
    object SalaryLesson10: Screen("salarylesson10")
    object SalaryLesson12: Screen("salarylesson12")
    object SalaryLesson13: Screen("salarylesson13")
    object SalaryLesson14: Screen("salarylesson14")
    object SalaryLesson15: Screen("salarylesson15")
    object SalaryLesson16: Screen("salarylesson16")
    object SalaryLesson17: Screen("salarylesson17")
    object SalaryLesson18: Screen("salarylesson18")
    object SalaryLesson19: Screen("salarylesson19")
    /*------------------------------------------------------------*/
    object AllawonceLevel0: Screen("allowancelevel0")
    object AllawonceLevel1: Screen("allowancelevel1")
    object AllawonceLevel2: Screen("allowancelevel2")
    object AllawonceLevel3: Screen("allowancelevel3")
    object AllawonceLevel4: Screen("allowancelevel4")
    object AllawonceLevel5: Screen("allowancelevel5")
    object AllawonceLevel6: Screen("allowancelevel6")
    object AllawonceLevel7: Screen("allowancelevel7")
    object AllawonceLevel8: Screen("allowancelevel8")
    object AllawonceLevel9: Screen("allowancelevel9")
    object SalaryLevel0: Screen("salarylevel0")
    object SalaryLevel1: Screen("salarylevel1")
    object SalaryLevel2: Screen("salarylevel2")
    object SalaryLevel3: Screen("salarylevel3")
    object SalaryLevel4: Screen("salarylevel4")
    object SalaryLevel5: Screen("salarylevel5")
    object SalaryLevel6: Screen("salarylevel6")
    object SalaryLevel7: Screen("salarylevel7")
    object SalaryLevel8: Screen("salarylevel8")
    object SalaryLevel9: Screen("salarylevel9")
    object SalaryLevel10: Screen("salarylevel10")
    object SalaryLevel11: Screen("salarylevel11")
    object SalaryLevel12: Screen("salarylevel12")
    object SalaryLevel13: Screen("salarylevel13")
    object SalaryLevel14: Screen("salarylevel14")
    object SalaryLevel15: Screen("salarylevel15")
    object SalaryLevel16: Screen("salarylevel16")
    object SalaryLevel17: Screen("salarylevel17")
    object SalaryLevel18: Screen("salarylevel18")
    object SalaryLevel19: Screen("salarylevel19")


}

